// File: lib/mock-data.js
// An expanded set of mock data with US-based names for better testing.

export const mockIncidents = [
  // Existing data, updated with new names
  { id: 1000029882, incidentType: 'SAP-CHANGE MGMT(TR)', location: 'Finance Dept, 2nd Floor', requestor: 'John Smith', priority: 'High', status: 'Processed', reportedOn: '07 Jun 25, 05:16 PM' },
  { id: 1000029878, incidentType: 'Password Reset', location: 'HR Wing, Building A', requestor: 'Emily Johnson', priority: 'High', status: 'Resolved', reportedOn: '07 Jun 25, 04:17 PM' },
  { id: 1000029875, incidentType: 'Hardware Failure', location: 'IT Server Room', requestor: 'Michael Williams', priority: 'High', status: 'Closed', reportedOn: '07 Jun 25, 12:19 PM' },
  { id: 1000029873, incidentType: 'Password Reset', location: 'Sales Department', requestor: 'Jessica Brown', priority: 'Medium', status: 'Resolved', reportedOn: '07 Jun 25, 10:02 AM' },
  { id: 1000029871, incidentType: 'Hardware Failure', location: 'Logistics Warehouse', requestor: 'David Jones', priority: 'High', status: 'Closed', reportedOn: '06 Jun 25, 06:32 PM' },
  { id: 1000029881, incidentType: 'SAP-USER ACCESS MGMT', location: 'Executive Suite', requestor: 'Sarah Garcia', priority: 'Medium', status: 'Processed', reportedOn: '07 Jun 25, 04:18 PM' },
  { id: 1000029880, incidentType: 'SAP-CHANGE MGMT(TR)', location: 'Finance Dept, 2nd Floor', requestor: 'James Miller', priority: 'High', status: 'Processed', reportedOn: '07 Jun 25, 05:17 PM' },
  { id: 1000029877, incidentType: 'Network Connectivity', location: 'Marketing Office', requestor: 'Linda Davis', priority: 'High', status: 'Resolved', reportedOn: '07 Jun 25, 04:18 PM' },
  { id: 1000029876, incidentType: 'NETWORK', location: 'Network Hub - Building C', requestor: 'Robert Rodriguez', priority: 'Medium', status: 'Resolved', reportedOn: '07 Jun 25, 01:01 PM' },
  { id: 1000029872, incidentType: 'Biometric Scan Error', location: 'Main Entrance', requestor: 'Patricia Martinez', priority: 'High', status: 'Processed', reportedOn: '06 Jun 25, 09:55 PM' },

  // 50 new records
  { id: 1000029890, incidentType: 'Software Installation', location: 'Marketing Office', requestor: 'William Hernandez', priority: 'Low', status: 'New', reportedOn: '08 Jun 25, 09:00 AM' },
  { id: 1000029891, incidentType: 'Email Issue', location: 'Sales Department', requestor: 'Elizabeth Lopez', priority: 'Medium', status: 'Processed', reportedOn: '08 Jun 25, 09:05 AM' },
  { id: 1000029892, incidentType: 'Printer Not Working', location: 'HR Wing, Building A', requestor: 'Joseph Gonzalez', priority: 'Medium', status: 'Pending', reportedOn: '08 Jun 25, 09:15 AM' },
  { id: 1000029893, incidentType: 'Network Connectivity', location: 'Logistics Warehouse', requestor: 'Jennifer Wilson', priority: 'High', status: 'Processed', reportedOn: '08 Jun 25, 09:20 AM' },
  { id: 1000029894, incidentType: 'Password Reset', location: 'Finance Dept, 2nd Floor', requestor: 'Thomas Anderson', priority: 'Medium', status: 'Resolved', reportedOn: '08 Jun 25, 09:30 AM' },
  { id: 1000029895, incidentType: 'SAP Access Request', location: 'Executive Suite', requestor: 'Mary Thomas', priority: 'High', status: 'Closed', reportedOn: '08 Jun 25, 09:45 AM' },
  { id: 1000029896, incidentType: 'Hardware Failure', location: 'IT Server Room', requestor: 'Christopher Taylor', priority: 'High', status: 'New', reportedOn: '08 Jun 25, 10:00 AM' },
  { id: 1000029897, incidentType: 'Biometric Scan Error', location: 'Warehouse Gate', requestor: 'Susan Moore', priority: 'Medium', status: 'Processed', reportedOn: '08 Jun 25, 10:10 AM' },
  { id: 1000029898, incidentType: 'Software Installation', location: 'Finance Dept, 2nd Floor', requestor: 'Daniel Jackson', priority: 'Low', status: 'Resolved', reportedOn: '08 Jun 25, 10:15 AM' },
  { id: 1000029899, incidentType: 'Email Issue', location: 'Marketing Office', requestor: 'Karen Martin', priority: 'Medium', status: 'Closed', reportedOn: '08 Jun 25, 10:30 AM' },
  { id: 1000029900, incidentType: 'Printer Not Working', location: 'Sales Department', requestor: 'Matthew Lee', priority: 'Medium', status: 'Processed', reportedOn: '08 Jun 25, 10:45 AM' },
  { id: 1000029901, incidentType: 'Network Connectivity', location: 'Executive Suite', requestor: 'Lisa Perez', priority: 'High', status: 'Pending', reportedOn: '08 Jun 25, 11:00 AM' },
  { id: 1000029902, incidentType: 'Password Reset', location: 'HR Wing, Building A', requestor: 'Anthony Thompson', priority: 'Medium', status: 'New', reportedOn: '08 Jun 25, 11:05 AM' },
  { id: 1000029903, incidentType: 'SAP Access Request', location: 'Finance Dept, 2nd Floor', requestor: 'Nancy White', priority: 'High', status: 'Resolved', reportedOn: '08 Jun 25, 11:20 AM' },
  { id: 1000029904, incidentType: 'Hardware Failure', location: 'Logistics Warehouse', requestor: 'Mark Harris', priority: 'High', status: 'Closed', reportedOn: '08 Jun 25, 11:35 AM' },
  { id: 1000029905, incidentType: 'Biometric Scan Error', location: 'Main Entrance', requestor: 'Betty Sanchez', priority: 'Medium', status: 'New', reportedOn: '08 Jun 25, 11:50 AM' },
  { id: 1000029906, incidentType: 'Software Installation', location: 'Sales Department', requestor: 'Donald Clark', priority: 'Low', status: 'Processed', reportedOn: '09 Jun 25, 12:00 PM' },
  { id: 1000029907, incidentType: 'Email Issue', location: 'Executive Suite', requestor: 'Dorothy Lewis', priority: 'Medium', status: 'Resolved', reportedOn: '09 Jun 25, 12:15 PM' },
  { id: 1000029908, incidentType: 'Printer Not Working', location: 'Marketing Office', requestor: 'Paul Robinson', priority: 'Medium', status: 'Closed', reportedOn: '09 Jun 25, 12:30 PM' },
  { id: 1000029909, incidentType: 'Network Connectivity', location: 'IT Server Room', requestor: 'Helen Walker', priority: 'High', status: 'Pending', reportedOn: '09 Jun 25, 12:45 PM' },
  { id: 1000029910, incidentType: 'Password Reset', location: 'Logistics Warehouse', requestor: 'George Young', priority: 'Medium', status: 'New', reportedOn: '09 Jun 25, 01:00 PM' },
  { id: 1000029911, incidentType: 'SAP Access Request', location: 'HR Wing, Building A', requestor: 'Sandra Allen', priority: 'High', status: 'Processed', reportedOn: '09 Jun 25, 01:15 PM' },
  { id: 1000029912, incidentType: 'Hardware Failure', location: 'Finance Dept, 2nd Floor', requestor: 'Kenneth King', priority: 'High', status: 'Resolved', reportedOn: '09 Jun 25, 01:30 PM' },
  { id: 1000029913, incidentType: 'Biometric Scan Error', location: 'Sales Department', requestor: 'Carol Wright', priority: 'Medium', status: 'Closed', reportedOn: '09 Jun 25, 01:45 PM' },
  { id: 1000029914, incidentType: 'Software Installation', location: 'Executive Suite', requestor: 'Steven Scott', priority: 'Low', status: 'Pending', reportedOn: '09 Jun 25, 02:00 PM' },
  { id: 1000029915, incidentType: 'Email Issue', location: 'IT Server Room', requestor: 'Donna Green', priority: 'Medium', status: 'New', reportedOn: '09 Jun 25, 02:15 PM' },
  { id: 1000029916, incidentType: 'Printer Not Working', location: 'Logistics Warehouse', requestor: 'Edward Adams', priority: 'Medium', status: 'Processed', reportedOn: '09 Jun 25, 02:30 PM' },
  { id: 1000029917, incidentType: 'Network Connectivity', location: 'HR Wing, Building A', requestor: 'Ruth Baker', priority: 'High', status: 'Resolved', reportedOn: '09 Jun 25, 02:45 PM' },
  { id: 1000029918, incidentType: 'Password Reset', location: 'Marketing Office', requestor: 'Brian Nelson', priority: 'Medium', status: 'Closed', reportedOn: '09 Jun 25, 03:00 PM' },
  { id: 1000029919, incidentType: 'SAP Access Request', location: 'Sales Department', requestor: 'Sharon Carter', priority: 'High', status: 'New', reportedOn: '09 Jun 25, 03:15 PM' },
  { id: 1000029920, incidentType: 'Hardware Failure', location: 'Executive Suite', requestor: 'Ronald Mitchell', priority: 'High', status: 'Processed', reportedOn: '09 Jun 25, 03:30 PM' },
  { id: 1000029921, incidentType: 'Biometric Scan Error', location: 'Finance Dept, 2nd Floor', requestor: 'Kimberly Roberts', priority: 'Medium', status: 'Resolved', reportedOn: '09 Jun 25, 03:45 PM' },
  { id: 1000029922, incidentType: 'Software Installation', location: 'IT Server Room', requestor: 'Kevin Turner', priority: 'Low', status: 'Closed', reportedOn: '10 Jun 25, 04:00 PM' },
  { id: 1000029923, incidentType: 'Email Issue', location: 'Logistics Warehouse', requestor: 'Deborah Phillips', priority: 'Medium', status: 'Pending', reportedOn: '10 Jun 25, 04:15 PM' },
  { id: 1000029924, incidentType: 'Printer Not Working', location: 'HR Wing, Building A', requestor: 'Jason Campbell', priority: 'Medium', status: 'New', reportedOn: '10 Jun 25, 04:30 PM' },
  { id: 1000029925, incidentType: 'Network Connectivity', location: 'Marketing Office', requestor: 'Michelle Parker', priority: 'High', status: 'Processed', reportedOn: '10 Jun 25, 04:45 PM' },
  { id: 1000029926, incidentType: 'Password Reset', location: 'Sales Department', requestor: 'Timothy Evans', priority: 'Medium', status: 'Resolved', reportedOn: '10 Jun 25, 05:00 PM' },
  { id: 1000029927, incidentType: 'SAP Access Request', location: 'Executive Suite', requestor: 'Laura Edwards', priority: 'High', status: 'Closed', reportedOn: '10 Jun 25, 05:15 PM' },
  { id: 1000029928, incidentType: 'Hardware Failure', location: 'Finance Dept, 2nd Floor', requestor: 'John Smith', priority: 'High', status: 'Pending', reportedOn: '10 Jun 25, 05:30 PM' },
  { id: 1000029929, incidentType: 'Biometric Scan Error', location: 'IT Server Room', requestor: 'Emily Johnson', priority: 'Medium', status: 'New', reportedOn: '11 Jun 25, 05:45 PM' },
  { id: 1000029930, incidentType: 'Software Installation', location: 'Logistics Warehouse', requestor: 'Michael Williams', priority: 'Low', status: 'Processed', reportedOn: '11 Jun 25, 06:00 PM' },
  { id: 1000029931, incidentType: 'Email Issue', location: 'HR Wing, Building A', requestor: 'Jessica Brown', priority: 'Medium', status: 'Resolved', reportedOn: '11 Jun 25, 06:15 PM' },
  { id: 1000029932, incidentType: 'Printer Not Working', location: 'Marketing Office', requestor: 'David Jones', priority: 'Medium', status: 'Closed', reportedOn: '11 Jun 25, 06:30 PM' },
  { id: 1000029933, incidentType: 'Network Connectivity', location: 'Sales Department', requestor: 'Sarah Garcia', priority: 'High', status: 'Pending', reportedOn: '11 Jun 25, 06:45 PM' },
  { id: 1000029934, incidentType: 'Password Reset', location: 'Executive Suite', requestor: 'James Miller', priority: 'Medium', status: 'New', reportedOn: '11 Jun 25, 07:00 PM' },
  { id: 1000029935, incidentType: 'SAP Access Request', location: 'Finance Dept, 2nd Floor', requestor: 'Linda Davis', priority: 'High', status: 'Processed', reportedOn: '12 Jun 25, 07:15 PM' },
  { id: 1000029936, incidentType: 'Hardware Failure', location: 'IT Server Room', requestor: 'Robert Rodriguez', priority: 'High', status: 'Resolved', reportedOn: '12 Jun 25, 07:30 PM' },
  { id: 1000029937, incidentType: 'Biometric Scan Error', location: 'Logistics Warehouse', requestor: 'Patricia Martinez', priority: 'Medium', status: 'Closed', reportedOn: '12 Jun 25, 07:45 PM' },
  { id: 1000029938, incidentType: 'Software Installation', location: 'HR Wing, Building A', requestor: 'William Hernandez', priority: 'Low', status: 'Pending', reportedOn: '12 Jun 25, 08:00 PM' },
  { id: 1000029939, incidentType: 'Email Issue', location: 'Marketing Office', requestor: 'Elizabeth Lopez', priority: 'Medium', status: 'New', reportedOn: '12 Jun 25, 08:15 PM' },
];