"use client";

import * as React from "react";
import { useParams } from "next/navigation";
import { useSession } from "next-auth/react";
import useSWR from "swr";
import { NotificationContext } from "@/context/NotificationContext";
import { Box, Stack, Typography, CircularProgress, Alert } from "@mui/material";
import IncidentDetailsCard from "@/components/IncidentDetailsCard";
import IncidentAuditTrail from "@/components/IncidentAuditTrail";
import IncidentActionForm from "@/components/IncidentActionForm";
import ResolutionDialog from "@/components/ResolutionDialog";
import ResetPasswordModal from "@/components/ResetPasswordModal";
import DescriptionModal from "@/components/DescriptionModal";
import {
  INCIDENT_STATUS,
  USER_ROLES,
  AUDIT_ACTIONS,
  INCIDENT_TYPES,
  DIALOG_CONTEXTS,
  RESOLUTION_ACTIONS,
} from "@/lib/constants";

const fetcher = (url) => fetch(url).then((res) => res.json());

const updateIncidentAPI = async (id, data) => {
  const response = await fetch(`/api/incidents/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });
  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.message || "Failed to update incident");
  }
  return response.json();
};

const editCommentAPI = async (id, entryId, newComment) => {
  const response = await fetch(`/api/incidents/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ action: "editAuditComment", entryId, newComment }),
  });
  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.message || "Failed to edit comment");
  }
  return response.json();
};

export default function IncidentDetailsPage() {
  const params = useParams();
  const { showNotification } = React.useContext(NotificationContext);
  const { data: session } = useSession();
  const user = session?.user;
  const {
    data: incidentData,
    error,
    isLoading,
    mutate,
  } = useSWR(params.id ? `/api/incidents/${params.id}` : null, fetcher, {
    refreshInterval:
      user?.role === "admin" || user?.role === "sys_admin" ? 15000 : 0,
    revalidateOnFocus: !(user?.role === "admin" || user?.role === "sys_admin"),
  });

  const incident = incidentData;
  //console.log("Full Incident Object:", incident);

  const [isDialogOpen, setDialogOpen] = React.useState(false);
  const [isResetModalOpen, setIsResetModalOpen] = React.useState(false);
  const [isOptimisticallyResolved, setOptimisticallyResolved] =
    React.useState(false); // Track optimistic resolution state
  const [isDescriptionModalOpen, setDescriptionModalOpen] =
    React.useState(false);
  const [dialogContext, setDialogContext] = React.useState("");

  const auditTrailRef = React.useRef(null);
  const [isAuditTrailExpanded, setIsAuditTrailExpanded] = React.useState(false);

  const handlePasswordResetSuccess = () => {
    setIsResetModalOpen(false); // This closes the modal
    mutate(); // This re-fetches all the incident data
    showNotification(
      "ESS Password has been reset successfully. User will be notified via email.",
      "success"
    );
  };

  React.useEffect(() => {
    setTimeout(() => {
      auditTrailRef.current?.scrollToBottom();
    }, 0);
  }, [incident?.auditTrail?.length]);

  const handleOpenDialog = (context) => {
    setDialogContext(context);
    setDialogOpen(true);
  };

  const handleUpdate = async (updateData) => {
    // Immediately exit if the comment is empty
    if (!updateData.comment || !updateData.comment.trim()) return;

    const payload = { ...updateData };
    if (incident?.status === INCIDENT_STATUS.NEW) {
      payload.status = INCIDENT_STATUS.PROCESSED;
    }

    // --- SIMPLIFIED OPTIMISTIC UI LOGIC ---

    // 1. Create a temporary audit entry for instant display in the UI.
    //    We use a simple random ID that is ONLY for React's internal list rendering.
    //    The real, permanent ID will be generated by the database.
    const optimisticAuditEntry = {
      id: "optimistic-" + Math.random(),
      author: user.name,
      action: AUDIT_ACTIONS.ACTION_TAKEN,
      comment: updateData.comment,
      timestamp: new Date().toISOString(), // Use the current time for instant display
    };

    // 2. Instantly update the UI with the temporary data
    mutate(
      (currentData) => ({
        ...currentData,
        status: payload.status || currentData.status,
        auditTrail: [...currentData.auditTrail, optimisticAuditEntry],
      }),
      false // Tell SWR not to re-fetch from the server immediately
    );

    // Instantly scroll the audit trail to the bottom
    setTimeout(() => auditTrailRef.current?.scrollToBottom(), 0);

    // 3. Send the real request to the server in the background.
    //    Notice we are NOT sending the temporary ID.
    try {
      await updateIncidentAPI(params.id, payload);

      // After the server succeeds, we run mutate() again without arguments.
      // This re-fetches the real data from the server, which will seamlessly
      // replace the temporary entry with the permanent one from the database.
      mutate();
    } catch (err) {
      showNotification(err.message, "error");
      // If the server fails, revert the UI to the original state
      mutate();
    }
  };

  const handleConfirmResolve = async (resolutionData) => {
    // This function now handles multiple actions from the dialog
    let payload = { ...resolutionData };

    switch (resolutionData.action) {
      case RESOLUTION_ACTIONS.ACCEPT_CLOSE:
        // User accepts the resolution, close the incident
        payload.status = INCIDENT_STATUS.CLOSED;
        break;

      case RESOLUTION_ACTIONS.RE_OPEN:
        // User is not satisfied, re-open the incident
        payload.status = INCIDENT_STATUS.PROCESSED;
        // Crucially, clear any existing rating
        payload.rating = null;
        break;

      case RESOLUTION_ACTIONS.CLOSE:
        // Admin or User is closing the incident directly
        payload.status = INCIDENT_STATUS.CLOSED;
        break;

      case RESOLUTION_ACTIONS.RESOLVE:
        // Admin is resolving the incident
        payload.status = INCIDENT_STATUS.RESOLVED;
        break;

      default:
        // Do nothing for unknown actions
        return;
    }

    // Optimistically update the UI before the API call
    if (resolutionData.action !== RESOLUTION_ACTIONS.RE_OPEN) {
      setOptimisticallyResolved(true);
    }

    try {
      await updateIncidentAPI(params.id, payload);
      showNotification("Incident updated successfully.", "success");
      mutate(); // Re-fetch data to get the final state
    } catch (err) {
      showNotification(err.message, "error");
      mutate(); // Revert any UI changes if the API fails
    } finally {
      setOptimisticallyResolved(false);
    }
  };

  const handleCommentEdit = async (entryId, newComment) => {
    if (!incident) return;
    try {
      await editCommentAPI(incident.id, entryId, newComment);
      mutate(); // Re-fetch data
    } catch (err) {
      showNotification(err.message, "error");
    }
  };

  if (!user) return null;
  if (isLoading) {
    return (
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          height: "calc(100vh - 200px)",
        }}
      >
        <CircularProgress />
      </Box>
    );
  }

  if (error) {
    return (
      <Alert severity="error" sx={{ m: 4 }}>
        Failed to load incident details.
      </Alert>
    );
  }

  if (!incident) {
    return (
      <Box sx={{ textAlign: "center", mt: 10 }}>
        <Typography variant="h4" color="error">
          Incident Not Found
        </Typography>
        <Typography>
          The incident with ID "{params.id}" could not be found.
        </Typography>
      </Box>
    );
  }

  const isResolved =
    incident.status === INCIDENT_STATUS.RESOLVED ||
    incident.status === INCIDENT_STATUS.CLOSED ||
    isOptimisticallyResolved;

  const canTakeAction =
    (user.role === USER_ROLES.ADMIN ||
      user.role === USER_ROLES.SYS_ADMIN ||
      user.role === USER_ROLES.NETWORK_VENDOR ||
      user.role === USER_ROLES.BIOMETRIC_VENDOR) &&
    !isResolved;

  // First, check if a password reset has already occurred.
  const isPasswordReset = incident.auditTrail.some(
    (entry) => entry.action === AUDIT_ACTIONS.PASSWORD_RESET
  );

  // Now, decide if the button should be shown.
  const showResetButton =
    canTakeAction &&
    incident?.incidentType?.name.toLowerCase() ===
      INCIDENT_TYPES.ESS_PASSWORD.toLowerCase() &&
    incident?.status !== INCIDENT_STATUS.NEW &&
    !isPasswordReset;

  const isRequestor = user?.ticketNo === incident?.requestor?.ticketNo;

  const canUserClose =
    isRequestor && incident.status === INCIDENT_STATUS.PROCESSED;

  const canUserConfirm =
    isRequestor && incident.status === INCIDENT_STATUS.RESOLVED;

  return (
    <>
      <Box
        sx={{
          display: "flex",
          gap: 3,
          alignItems: "stretch",
          height: "calc(100vh - 112px)",
        }}
      >
        <Box sx={{ flex: 7, minWidth: 0 }}>
          <IncidentDetailsCard
            incident={incident}
            onOpenDescriptionModal={() => setDescriptionModalOpen(true)}
          />
        </Box>
        {canTakeAction || isRequestor ? (
          <Stack
            spacing={0}
            sx={{ flex: 5, minWidth: 0, position: "relative" }}
          >
            <Box
              sx={{
                flexGrow: 1,
                minHeight: 0,
                display: "flex",
                position: "relative",
                zIndex: 2,
              }}
            >
              <IncidentAuditTrail
                ref={auditTrailRef}
                auditTrail={incident.auditTrail || []}
                incident={incident}
                isResolved={isResolved}
                onCommentEdit={handleCommentEdit}
                isExpanded={isAuditTrailExpanded}
                onToggleExpand={() => setIsAuditTrailExpanded((prev) => !prev)}
              />
            </Box>

            {!isAuditTrailExpanded && (
              <IncidentActionForm
                incident={incident}
                onUpdate={handleUpdate}
                // Passing a generic handler for Admins
                onOpenResolveDialog={() =>
                  handleOpenDialog(DIALOG_CONTEXTS.ADMIN_RESOLVE_CLOSE)
                }
                showResetButton={showResetButton}
                onOpenResetDialog={() => setIsResetModalOpen(true)}
                // --- Start: New props for the standard user ---
                isRequestor={isRequestor}
                canUserClose={canUserClose}
                onUserClose={() => handleOpenDialog(DIALOG_CONTEXTS.USER_CLOSE)}
                canUserConfirm={canUserConfirm}
                onUserConfirm={() =>
                  handleOpenDialog(DIALOG_CONTEXTS.USER_CONFIRM_RESOLUTION)
                }
                isDisabled={
                  incident.status === INCIDENT_STATUS.NEW && isRequestor
                }
                // --- End: New props for the standard user ---
              />
            )}
          </Stack>
        ) : (
          <Box sx={{ flex: 5, minWidth: 0, display: "flex" }}>
            <IncidentAuditTrail
              ref={auditTrailRef}
              auditTrail={incident.auditTrail || []}
              incident={incident}
              isResolved={isResolved}
              onCommentEdit={handleCommentEdit}
              isExpanded={false}
              onToggleExpand={() => {}}
            />
          </Box>
        )}
      </Box>
      <ResolutionDialog
        open={isDialogOpen}
        onClose={() => setDialogOpen(false)}
        onConfirm={handleConfirmResolve}
        context={dialogContext}
      />
      <ResetPasswordModal
        open={isResetModalOpen}
        onClose={() => setIsResetModalOpen(false)}
        incident={incident}
        onSuccess={handlePasswordResetSuccess}
      />
      <DescriptionModal
        open={isDescriptionModalOpen}
        onClose={() => setDescriptionModalOpen(false)}
        description={incident?.description}
      />
    </>
  );
}
